__nativedecl(vlibc) void abort();
__nativedecl(vlibc) void exit(int exit_code);
__nativedecl(vlibc) void quick_exit(int exit_code);
__nativedecl(vlibc) void _Exit(int exit_code);
__nativedecl(vlibc) int system(const char* command);
__nativedecl(vlibc) char* getenv(const char* env_var);
//__nativedecl(vlibc) void* malloc(size_t size);
//__nativedecl(vlibc) void* aligned_malloc(size_t alignment, size_t size);
//__nativedecl(vlibc) void* calloc(size_t num, size_t size);
//__nativedecl(vlibc) void* realloc(void* ptr, size_t new_size);
//__nativedecl(vlibc) void free(void* ptr);
__nativedecl(vlibc) int atoi(const char* str);
__nativedecl(vlibc) long atol(const char* str);
__nativedecl(vlibc) long long atoll(const char* str);
__nativedecl(vlibc) long strtol(const char* str, char** str_end, int base);
__nativedecl(vlibc) long long strtoll(const char* str, char** str_end, int base);
//__nativedecl(vlibc) unsigned long strtoul(const char* str, char** str_end, int base);
//__nativedecl(vlibc) unsigned long long strtoull(const char* str, char** str_end, int base);
__nativedecl(vlibc) int rand();
__nativedecl(vlibc) void srand();
__nativedecl(vlibc) int abs(int num);
__nativedecl(vlibc) long labs(long num);
__nativedecl(vlibc) long long llabs(long long num);
